function [I2Mfout, varargout] = ab2vega(varargin)
%
% % File generated by IDL2Matlab 1.6 130501 %%

% %Initialization of parameters
  I2Mkwn=char('I2M_a1', 'I2M_a2', 'I2M_pos');
  I2Mkwv={'mab', 'l', 'I2M_pos'};
  mab=[]; l=[]; I2M_pos=[];
  I2M_lst={}; I2M_out=''; lv=length(varargin); if rem(lv,2) ~= 0, I2M_ok=0; else, I2M_ok=1;
  for I2M=1:2:lv; I2M_tmp=varargin{I2M}; if ~ischar(I2M_tmp); I2M_ok=0; break; end; I2Mx=strmatch(I2M_tmp,I2Mkwn); if length(I2Mx) ~=1; I2M_ok=0; break; end; eval([I2Mkwv{I2Mx} '=varargin{I2M+1};']); I2M_lst{(I2M+1)/2}=I2Mkwv{I2Mx}; end; end;
  if ~I2M_ok; for I2M=1:lv; eval([I2Mkwv{I2M} '=varargin{I2M};']); end; end;
  if ~isempty(I2M_pos); for I2M=1:length(I2M_pos); I2Ms=num2str(I2M); I2M_out=[I2M_out 'varargout{' I2Ms '}=' I2M_lst{I2M_pos(I2M)} '; ']; end; end;

% % End of parameters initialization


  % vega reference spectrum from calspec (bohlin 2007):
  readcol('~/Idl/GHOST_ETC/RefData/alpha_lyr_stis_004.ascii',lvega,fvega,1);
  [mabvega, l] = flux2ab('I2M_a1', interpol(fvega,lvega,l), 'I2M_a2', l, 'I2M_pos', [2]);
  if ~isempty(I2M_out),eval(I2M_out);end;I2Mfout = mab - mabvega;
  return;
% % end of function ab2vega
