function [I2Mfout, varargout] = flux2ab(varargin)
%
% File generated by IDL2Matlab 1.6 130501 %%

% %Initialization of parameters
  I2Mkwn=char('I2M_a1', 'I2M_a2', 'si', 'arcsec', 'I2M_pos');
  I2Mkwv={'flux', 'lbda', 'si', 'arcsec', 'I2M_pos'};
  flux=[]; lbda=[]; si=[]; arcsec=[]; I2M_pos=[];
  I2M_lst={}; I2M_out=''; lv=length(varargin); if rem(lv,2) ~= 0, I2M_ok=0; else, I2M_ok=1;
  for I2M=1:2:lv; I2M_tmp=varargin{I2M}; if ~ischar(I2M_tmp); I2M_ok=0; break; end; I2Mx=strmatch(I2M_tmp,I2Mkwn); if length(I2Mx) ~=1; I2M_ok=0; break; end; eval([I2Mkwv{I2Mx} '=varargin{I2M+1};']); I2M_lst{(I2M+1)/2}=I2Mkwv{I2Mx}; end; end;
  if ~I2M_ok; for I2M=1:lv; eval([I2Mkwv{I2M} '=varargin{I2M};']); end; end;
  if ~isempty(I2M_pos); for I2M=1:length(I2M_pos); I2Ms=num2str(I2M); I2M_out=[I2M_out 'varargout{' I2Ms '}=' I2M_lst{I2M_pos(I2M)} '; ']; end; end;

% % End of parameters initialization


  % lbda is in a
  % flux is in erg/s/cm2 if option si is not set
  % flux is in kg/m/sec3 if option si is set
  % flux is in arcsec-2 if option sec is set
  % flux is in a-1 if option a is set
  % result is ab magnitude
  c = 299792458.0;  % in m/s
  l = lbda .* 1.e-10;  % in m
  M2I_asec = 1.0 ./ 206265.0;  % arcsec in radian
  f = flux;
  if (keyword_set(arcsec))

    f = flux .* M2I_asec.^2;
  end%if

  if ( ~keyword_set(si))

    ab = -73.60 - 2.5 .* log10(l.^2 .* f ./ c);
  
  else

    ab = -56.10 - 2.5 .* log10(l.^2 .* f ./ c);
  end%if

  if ~isempty(I2M_out),eval(I2M_out);end;I2Mfout = ab;
  return;
% % end of function flux2ab
