function [varargout] = print_noise(varargin)
%
% File generated by IDL2Matlab 1.6 130501 %%

% %Initialization of parameters
  I2Mkwn=char('I2M_a1', 'I2M_a2', 'I2M_a3', 'I2M_a4', 'I2M_pos');
  I2Mkwv={'vobj', 'vsky', 'vrn', 'vdc', 'I2M_pos'};
  vobj=[]; vsky=[]; vrn=[]; vdc=[]; I2M_pos=[];
  I2M_lst={}; I2M_out=''; lv=length(varargin); if rem(lv,2) ~= 0, I2M_ok=0; else, I2M_ok=1;
  for I2M=1:2:lv; I2M_tmp=varargin{I2M}; if ~ischar(I2M_tmp); I2M_ok=0; break; end; I2Mx=strmatch(I2M_tmp,I2Mkwn); if length(I2Mx) ~=1; I2M_ok=0; break; end; eval([I2Mkwv{I2Mx} '=varargin{I2M+1};']); I2M_lst{(I2M+1)/2}=I2Mkwv{I2Mx}; end; end;
  if ~I2M_ok; for I2M=1:lv; eval([I2Mkwv{I2M} '=varargin{I2M};']); end; end;
  if ~isempty(I2M_pos); for I2M=1:length(I2M_pos); I2Ms=num2str(I2M); I2M_out=[I2M_out 'varargout{' I2Ms '}=' I2M_lst{I2M_pos(I2M)} '; ']; end; end;

% %End of parameters initialization


  %
  % description
  % compute and print break down of noise variance contributions coming from the
  % different components, all given as a fraction of the total.
  %
  % inputs
  % vobj - variance of object flux
  % vsky - variance of sky flux
  % vrn - variance of read noise
  % vdc - variance of dark current
  %
  %===================================================================================
  vtot = vobj + vsky + vrn + vdc;
  printt('format', '("Noise variance statistics - Obj:",f5.1,"% Sky:",f5.1,"% Detector:",f5.1,"% [RN:",f5.1, "% DC:",f5.1,"]")', 'I2M_a1', 100 .* vobj ./ vtot, 'I2M_a2', 100 .* vsky ./ vtot, 'I2M_a3', 100 .* (vrn + vdc) ./ vtot, 'I2M_a4', 100 .* vrn ./ vtot, 'I2M_a5', 100 .* vdc ./ vtot);
  [vdc, vrn, vsky, vobj] = printt('format', '("Noise variance statistics - Obj:",f7.1,"e- Sky:",f7.1,"e- Detector:",f7.1,"e- [RN:",f7.1, "e- DC:",f7.1,"e-]")', 'I2M_a1', vobj, 'I2M_a2', vsky, 'I2M_a3', (vrn + vdc), 'I2M_a4', vrn, 'I2M_a5', vdc, 'I2M_pos', [6, 5, 3, 2]);

if ~isempty(I2M_out),eval(I2M_out);end;
 return;
% % end of function print_noise
