function [I2Mfout, varargout] = sky(varargin)
%
% File generated by IDL2Matlab 1.6 130501 %%

% %Initialization of parameters
  I2Mkwn=char('I2M_a1', 'print', 'dir', 'bright', 'I2M_pos');
  I2Mkwv={'lmu', 'M2I_print', 'M2I_dir', 'bright', 'I2M_pos'};
  lmu=[]; M2I_print=[]; M2I_dir=[]; bright=[]; I2M_pos=[];
  I2M_lst={}; I2M_out=''; lv=length(varargin); if rem(lv,2) ~= 0, I2M_ok=0; else, I2M_ok=1;
  for I2M=1:2:lv; I2M_tmp=varargin{I2M}; if ~ischar(I2M_tmp); I2M_ok=0; break; end; I2Mx=strmatch(I2M_tmp,I2Mkwn); if length(I2Mx) ~=1; I2M_ok=0; break; end; eval([I2Mkwv{I2Mx} '=varargin{I2M+1};']); I2M_lst{(I2M+1)/2}=I2Mkwv{I2Mx}; end; end;
  if ~I2M_ok; for I2M=1:lv; eval([I2Mkwv{I2M} '=varargin{I2M};']); end; end;
  if ~isempty(I2M_pos); for I2M=1:length(I2M_pos); I2Ms=num2str(I2M); I2M_out=[I2M_out 'varargout{' I2Ms '}=' I2M_lst{I2M_pos(I2M)} '; ']; end; end;

% % End of parameters initialization

  % Creation of undeclared variables of functions parameters
  x1=1; y=1; 


  %
  % return the sky flux from hanuschik 2003.
  % optionally make a plot, via print keyword.
  % bright keyword scales the hanuschik continuum flux according to
  readcol('~/Idl/GHOST_ETC/RefData/hanuschik_cont_tab.dat',x1,x2,y,1);
  res = poly_fit(d1_array(x1,x2) ./ 1.e4,d1_array(y,y),3,yfit);
  sky = res(3 +1) .* lmu.^3 + res(2 +1) .* lmu.^2 + res(1 +1) .* lmu + res(0 +1);
  if (keyword_set(bright))

    wv = d1_array(3656.,4353.,5477.,6349.,8797.,10000.);
    dk = d1_array(22.5,22.8,21.8,20.9,19.7,19.3);
    brt = d1_array(19.3,19.1,18.5,18.2,17.3,16.9);
    delt = dk - brt;
    scl = 10..^(0.4 .* delt);
    res2 = poly_fit(wv ./ 1.e4,scl,3,yfit);
    brtcor = res2(3 +1) .* lmu.^3 + res2(2 +1) .* lmu.^2 + res2(1 +1) .* lmu + res2(0 +1);
    sky = sky .* brtcor;
  end%if

  if (keyword_set(M2I_print))

    if ( ~keyword_set(M2I_dir))
      M2I_dir = './';
    end%if
    pfile = M2I_dir + 'hanuschick.ps';
    set_ps(1,pfile,1);
    setplot_paper;
    [y, x1] = plott('I2M_a1', x1, 'I2M_a2', y, 'nodata', 1, 'xrange', d1_array(3000,10500), 'xsty', 1, 'xtitle', 'Wavelength ' + '(' + cgsymbol('angstrom') + ')', 'ytitle', 'Flux (10!U-16!N erg/s/cm!U2!N/' + cgsymbol('angstrom') + '/arcsec!U2!N)', 'title', 'Sky Continuum Brightness', 'yrange', d1_array(0,100), 'I2M_pos', [2, 1]);
    for i = 0:eval('n_elements(x1)','0') - 1,

      oplott('I2M_a1', d1_array(x1(i +1),x2(i)), 'I2M_a2', d1_array(y(i +1),y(i +1)), 'col', cgcolor('magenta'), 'thick', 15);
    end% for

    xplot = range(3000.,11000.) ./ 1.e4;
    yplot = res(3 +1) .* xplot.^3 + res(2 +1) .* xplot.^2 + res(1 +1) .* xplot + res(0 +1);
    if (keyword_set(bright))
      yplot = res2(3 +1) .* xplot.^3 + res2(2 +1) .* xplot.^2 + res2(1 +1) .* xplot + res2(0 +1);
    end%if
    [yplot] = oplott('I2M_a1', xplot .* 1.e4, 'I2M_a2', yplot, 'col', cgcolor('black'), 'thick', 5, 'I2M_pos', [2]);
    oplott('I2M_a1', d1_array(3400,3800), 'I2M_a2', d1_array(0.05,0.05), 'thick', 5);
    xyouts(d1_array(3900),d1_array(0.048),strung('I2M_a1', reverse(res), 'format', '("y = ",f5.2,"x!U3!N",f+5.2,"x!U2!N",f+5.2,"x",f+5.2)'));
    oplott('I2M_a1', d1_array(3400,3800), 'I2M_a2', d1_array(0.04,0.04), 'thick', 15, 'col', cgcolor('magenta'));
    xyouts(d1_array(3900),d1_array(0.038),'Mean sky flux (Hanuschik, 2003)');
    set_ps(1,pfile,1);
    [res] = printt('I2M_a1', res, 'I2M_pos', [1]);
  end%if

  if ~isempty(I2M_out),eval(I2M_out);end;I2Mfout = sky .* 1.e-16;
  return;
% % end of function sky
